### ISSUE TITLE
?crop should be the default

### ISSUE THREAD

**Issue by bpierre** [lisezmoi/scri.ch#18]
The [?crop parameter](https://github.com/lisezmoi/scri.ch#crop) is what we want most of the time. Also, some tools relies on the URL extension to determine the content type.

We should remove this parameter and make it the default when calling a drawing with `/xyz.png`. Also, if a drawing has no background (transparent), the cropped image should have a white background, unless the user has explicitely specified `background=transparent`.

The raw drawing could be moved to something like `/xyz-raw.png`.

**Comment by raphaelbastide** [comment]
I agree.

`/xyz-raw.png` is nice. Alternatives, just to be sure to list all the unwanted formats: `/xyz.raw.png` , `/raw/xyz.png`, `/xyz_.png`, `/raw-xyz.png`…

**Comment by bpierre** [comment]
Done https://github.com/lisezmoi/scri.ch/commit/a5f3a8bb1caa167c1729f15a2d5865ade36dbe5b
