### ISSUE TITLE
Safari iOS sometimes crash when saving

### ISSUE THREAD

**Issue by bpierre** [lisezmoi/scri.ch#2]

**Comment by bpierre** [comment]
Seems OK now with iOS 5. @raphaelbastide do you confirm?

**Comment by raphaelbastide** [comment]
Still crashing on my ipad with http://scri.ch/89q for instance

**Comment by bpierre** [comment]
iOS 5?

**Comment by raphaelbastide** [comment]
NOPE! I don't have it yet, can't test.

**Comment by bpierre** [comment]
Ok, so I assume it will work, Safari iOS 5 is a [big update](http://blog.newrelic.com/wp-content/uploads/New-Relic_iOS.png).

(Reopen this issue if Safari iOS 5 still crashes.)
