### ISSUE TITLE
Idea: Straight line

### ISSUE THREAD

**Issue by raphaelbastide** [lisezmoi/scri.ch#20]
One double click/tap here and one double click/tap there could render a straight ligne!

<img src="http://scri.ch/gm9.png?crop">

**Comment by bpierre** [comment]
Cool and interesting, but I see two issues:

What about point-based drawings? It’s very common to click twice at the same location by mistake:
![](http://scri.ch/gme.png?crop)

How to handle accidental double clicks, and maybe more frequent, double taps?

Possible solution: a new URL parameter to activate the double click / line mode.

**Comment by raphaelbastide** [comment]
> What about point-based drawings? It’s very common to click twice at the same location by mistake

I am not sure double click on a same pixel is really common.

> How to handle accidental double clicks, and maybe more frequent, double taps?

We can imagine a visual feedback: when a point is double-clicked it becomes blue, at this point it means that scri.ch is waiting for a second double click to trace the line. In the case of an accident, it can allow the user to correct the drawing depending on what he really want.

> Possible solution: a new URL parameter to activate the double click / line mode.

Well, it is wierd to have strait-line only drawing.
Imagine this drawing using straight lines for typography:

<img src="http://scri.ch/gmi.png?crop#stpd-limechat.png">

**Comment by bpierre** [comment]
> I am not sure double click on a same pixel is really common.

I am talking about the point-drawing technique. Maybe it’s not common, but I don’t think it’s rare. We can can measure that.

> We can imagine a visual feedback: when a point is double-clicked it becomes blue, at this point it means that scri.ch is waiting for a second double click to trace the line. In the case of an accident, it can allow the user to correct the drawing depending on what he really want.

I see, maybe we should test this.

The only thing that bores me is that it is the only core feature which is not understandable by itself (URL params are similar, but they are optional): nothing tells you why the dot is blue (but we could live-preview the line, in grey, to fix that), and more important: how did you triggered this.

We could add tips in the `<title>`, e.g. “The double-click/tap activated the line mode! Double-click/tap elsewhere to draw a straight line, or single click/tap to cancel.”

> Well, it is wierd to have strait-line only drawing.

The URL param would only activate the double-click feature, you still have the normal drawing.

---

Another thought, about the discoverability (we don’t care much about that though). A new user could try to double-click on the blank page to see what happens ↣ buttons are displayed ↣ the user tries to move its mouse cursor ↣ a blue dot appears under the mouse (or, a line follows the cursor) ↣ a simple click make it disappear ↣ confusion.

And a last one: if we add lines, what about rectangles? They could be really useful too, I’d really like to have them sometimes. But it will add another tool, and scri.ch is (for now) a zero-tool drawing tool :-)

---

Note: I’d really like to have straight lines (as I’d like to have an eraser tool), but I think it could be a direction change for scri.ch, so I want to be sure that every issue has been discussed.

**Comment by raphaelbastide** [comment]
After a private talk with @bpierre , It looks like adding a tool is not in the scri.ch’s state of mind. Let’ keep it on the side, at least for now.
