### ISSUE TITLE
Url tricks

### ISSUE THREAD

**Issue by raphaelbastide** [lisezmoi/scri.ch#5]
- size
- margin
- background color (white or transparent)

**Comment by bpierre** [comment]
Syntax examples:

```
// New drawing
http://scri.ch/?bg=000&fg=fff&margin=10&size=100x100

// Existing drawing
http://scri.ch/123/?margin=10
```

`bg`: Background color (hex) (default is transparent). Only available for new drawings.
`fg`: Foreground color (hex). Only available for new drawings.
`size`: Canvas dimensions (width x height). Available for new and existing drawings.
`margin`: Canvas margin. Available for new and existing drawings.

**Comment by bpierre** [comment]
Done: https://github.com/bpierre/scri.ch/commit/25e973cfea7eef5bef2ac3a4583ec37d9d661622
