### ISSUE TITLE
2 more IOS icons

### ISSUE THREAD

**Issue by raphaelbastide** [lisezmoi/scri.ch#6]
A 72x72px and a 114x114px icon

**Comment by raphaelbastide** [comment]
Still need to link this icons <a href="http://mathiasbynens.be/notes/touch-icons">this way</a> ?

**Comment by bpierre** [comment]
Yes, precomposed icons with these sizes:

```
114×114 (iPhone 4)
72×72   (iPad)
57×57   (other iOS devices + Android)
```

**Comment by raphaelbastide** [comment]
I think we can close this issue?
— > https://github.com/lisezmoi/scri.ch/commit/3c1b0808630f3c709f9b623465b39f9ad9e96fa1

**Comment by bpierre** [comment]
Yep
