### ISSUE TITLE
[?] link review

### ISSUE THREAD

**Issue by raphaelbastide** [lisezmoi/scri.ch#7]
![button review](http://scri.ch/7or.png) ![button review](http://scri.ch/7ot.png)

What about following a mini grid system for the buttons placement ?
This way [?] link can be more accessible for fingers and noob cursors and a bit more present for future secret features ;-)

**Comment by bpierre** [comment]
Totally agree, let’s do that =)

**Comment by raphaelbastide** [comment]
A. New grid
<img src="http://i.imgur.com/dOUEi.gif">

B. New [?] position
<img src="http://i.imgur.com/q36Iw.gif">

C. Old grid, new [?] position
<img src="http://i.imgur.com/lD6k9.gif">

D. What a strict grid can be
<img src="http://i.imgur.com/9hoZM.gif">

I think C is better. D is odd and almost impossible to use. C is a good balance between space and function.

**Comment by bpierre** [comment]
C > B > A

**Comment by raphaelbastide** [comment]
A = B

**Comment by bpierre** [comment]
C > D > A
